spring:
  ai:
    model:
      chat: openai
      audio:
        speech: openai
    openai:
      base-url: ${OPENAI_BASE_URL:https://i.alal.site/v1beta/openai}
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: ${OPENAI_MODEL:gemini-2.5-flash}
        completions-path: ${COMPLETIONS_PATH:/chat/completions}
      audio:
        speech:
          base-url: ${OPENAI_SPEECH_URL:https://i.alal.site/v1beta/openai}
          api-key: ${OPENAI_SPEECH_KEY:}
          options:
            model: ${OPENAI_SPEECH_MODEL:whisper-1}
            voice: ${OPENAI_VOICE:alloy}
            speed: ${OPENAI_SPEED:1.0}
  application:
    name: GTool
  thymeleaf:
    cache: true
server:
  port: 5010
#log config
logging:
  level:
    com.way: info
    root: info
  file:
    name: ./logs/gtool.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 120MB
      # max-history: 30
      total-size-cap: 3GB
gtool:
  host: ${GTOOL_HOST:http://localhost:5010}